name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.3/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.3/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.3/x64/lib

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest-xml-reporting

    - name: Run tests
      run: |
        python -m unittest discover -s. > test-results.xml
      continue-on-error: true

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml
      if-no-files-found: warn
      compression-level: 6
      overwrite: false
